# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties

# The Minecraft version must agree with the Forge version to get a valid artifact
minecraft_version=1.21.3
# The Minecraft version range can use any release version of Minecraft as bounds.
minecraft_version_range=[1.21.2,1.21.3)
# The Forge version must agree with the Minecraft version to get a valid artifact
forge_version=53.1.0
# The Forge version range can use any version of Forge as bounds
forge_version_range=[0,)
# The loader version range can only use the major version of Forge/FML as bounds
loader_version_range=[0,)
# The mapping channel to use for mappings. Supported: official, snapshot, stable, parchment
mapping_channel=official
# The mapping version to query from the mapping channel
mapping_version=1.21.3

## Mod Properties

# Unique mod identifier (lowercase, regex: [a-z][a-z0-9_]{1,63})
mod_id=orbitalradish
# Human-readable display name
mod_name=Orbital's Radish Mod
# License of the mod
mod_license=MIT
# Mod version (use semantic versioning)
mod_version=1.0.0
# Group ID for Maven publishing
mod_group_id=com.orbital
# Authors of the mod
mod_authors=orbital
# Description of the mod
mod_description=A mod I made for my best friend RadishStick
