org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neoforge_version=21.1.80
neoforge_version_range=[21.1,)
loader_version_range=[4,)

mod_id=orbitalradish
mod_name=Orbital's Radish Mod
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.orbital
mod_authors=orbital
mod_description=A mod I made for my best friend RadishStick