# This is the mods.toml file for OrbitalRadishMod

modLoader="javafml" #mandatory
loaderVersion="[53.1.0,)"
license="MIT" #mandatory

[[mods]]
modId="orbitalradish" #mandatory
version="1.0.0" #mandatory - your mod version
displayName="Orbital's Radish Mod" #mandatory
authors="orbital" #optional
description='''A mod I made for my best friend RadishStick''' #mandatory
displayTest="MATCH_VERSION" #default - warns if client/server versions differ

[[dependencies.orbitalradish]]
modId="forge" #mandatory
mandatory=true
versionRange="[53.1.0,)" #matches loaderVersion above
ordering="NONE"
side="BOTH"

[[dependencies.orbitalradish]]
modId="minecraft" #mandatory
mandatory=true
versionRange="[1.21.3,)"
ordering="NONE"
side="BOTH"
