# This is the mods.toml file for OrbitalRadishMod

modLoader="javafml" #mandatory
loaderVersion="[49.0.3,)" #mandatory - Forge 49.0.3 corresponds to Minecraft 1.20.4
license="MIT" #mandatory

[[mods]]
modId="orbitalradish" #mandatory
version="1.0.0" #mandatory - your mod version
displayName="Orbital's Radish Mod" #mandatory
authors="orbital" #optional
description='''A mod I made for my best friend RadishStick''' #mandatory
displayTest="MATCH_VERSION" #default - warns if client/server versions differ

[[dependencies.orbitalradish]]
modId="forge" #mandatory
mandatory=true
versionRange="[49.0.3,)" #matches loaderVersion above
ordering="NONE"
side="BOTH"

[[dependencies.orbitalradish]]
modId="minecraft" #mandatory
mandatory=true
versionRange="[1.20.4,2.0)" #minimum 1.20.4, less than 2.0
ordering="NONE"
side="BOTH"
