modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="orbitalradish"
version="1.0.0"
displayName="Orbital's Radish Mod"
authors="orbital"
description='''A mod I made for my best friend RadishStick'''

[[dependencies.orbitalradish]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.orbitalradish]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"